"""empty message

Revision ID: 480bf9d0a3eb
Revises: 
Create Date: 2020-07-04 17:07:21.470669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480bf9d0a3eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'short_link', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'workshop', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshop', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'short_link', type_='unique')
    # ### end Alembic commands ###
