"""empty message

Revision ID: 480bf9d0a3eb
Revises: 
Create Date: 2020-07-04 17:07:21.470669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480bf9d0a3eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'short_link', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'workshop', ['id'])
    '''
    Only run if you database columns were created before string size changes
    op.alter_column('workshop', 'text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500))
    op.alter_column('workshop', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80))
    op.alter_column('workshop', 'url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80))
    op.alter_column('workshop', 'workshopMD',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150))
    '''
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshop', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'short_link', type_='unique')
    # ### end Alembic commands ###
    #pass
